--- #change port
server:
  port: 8089
  
--- #view
spring:  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
      
--- #devtools
spring:
  devtools:
    livereload:      enabled: true
    restart:
      enabled: false
      
--- #jdbc
spring:
  datasource:    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/webdb
    username: webuser
    password: webuser
    
--- #mybatis mapper xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:    map-underscore-to-camel-case: true
